# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kps_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kps_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kem_pb2 as kem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11kps_service.proto\x12\x04\x64\x63sm\x1a\tkem.proto\"\xd7\x01\n\x15ProcessRawDataRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x13\n\x0braw_content\x18\x03 \x01(\x0c\x12J\n\x10initial_metadata\x18\x04 \x03(\x0b\x32\x30.dcsm.ProcessRawDataRequest.InitialMetadataEntry\x1a\x36\n\x14InitialMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Q\n\x16ProcessRawDataResponse\x12\x0e\n\x06kem_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x16\n\x0estatus_message\x18\x03 \x01(\t2h\n\x19KnowledgeProcessorService\x12K\n\x0eProcessRawData\x12\x1b.dcsm.ProcessRawDataRequest\x1a\x1c.dcsm.ProcessRawDataResponseB;Z9github.com/your_org/dcsm_protos/gen/go/kps;kps_service_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kps_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/your_org/dcsm_protos/gen/go/kps;kps_service_pb'
  _globals['_PROCESSRAWDATAREQUEST_INITIALMETADATAENTRY']._loaded_options = None
  _globals['_PROCESSRAWDATAREQUEST_INITIALMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_PROCESSRAWDATAREQUEST']._serialized_start=39
  _globals['_PROCESSRAWDATAREQUEST']._serialized_end=254
  _globals['_PROCESSRAWDATAREQUEST_INITIALMETADATAENTRY']._serialized_start=200
  _globals['_PROCESSRAWDATAREQUEST_INITIALMETADATAENTRY']._serialized_end=254
  _globals['_PROCESSRAWDATARESPONSE']._serialized_start=256
  _globals['_PROCESSRAWDATARESPONSE']._serialized_end=337
  _globals['_KNOWLEDGEPROCESSORSERVICE']._serialized_start=339
  _globals['_KNOWLEDGEPROCESSORSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
