# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import swm_service_pb2 as swm__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in swm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SharedWorkingMemoryServiceStub(object):
    """Shared Working Memory Service (SWM)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishKEMToSWM = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/PublishKEMToSWM',
                request_serializer=swm__service__pb2.PublishKEMToSWMRequest.SerializeToString,
                response_deserializer=swm__service__pb2.PublishKEMToSWMResponse.FromString,
                _registered_method=True)
        self.SubscribeToSWMEvents = channel.unary_stream(
                '/dcsm.SharedWorkingMemoryService/SubscribeToSWMEvents',
                request_serializer=swm__service__pb2.SubscribeToSWMEventsRequest.SerializeToString,
                response_deserializer=swm__service__pb2.SWMMemoryEvent.FromString,
                _registered_method=True)
        self.QuerySWM = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/QuerySWM',
                request_serializer=swm__service__pb2.QuerySWMRequest.SerializeToString,
                response_deserializer=swm__service__pb2.QuerySWMResponse.FromString,
                _registered_method=True)
        self.LoadKEMsFromGLM = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/LoadKEMsFromGLM',
                request_serializer=swm__service__pb2.LoadKEMsFromGLMRequest.SerializeToString,
                response_deserializer=swm__service__pb2.LoadKEMsFromGLMResponse.FromString,
                _registered_method=True)
        self.AcquireLock = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/AcquireLock',
                request_serializer=swm__service__pb2.AcquireLockRequest.SerializeToString,
                response_deserializer=swm__service__pb2.AcquireLockResponse.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/ReleaseLock',
                request_serializer=swm__service__pb2.ReleaseLockRequest.SerializeToString,
                response_deserializer=swm__service__pb2.ReleaseLockResponse.FromString,
                _registered_method=True)
        self.GetLockInfo = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/GetLockInfo',
                request_serializer=swm__service__pb2.GetLockInfoRequest.SerializeToString,
                response_deserializer=swm__service__pb2.LockInfo.FromString,
                _registered_method=True)
        self.IncrementCounter = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/IncrementCounter',
                request_serializer=swm__service__pb2.IncrementCounterRequest.SerializeToString,
                response_deserializer=swm__service__pb2.CounterValueResponse.FromString,
                _registered_method=True)
        self.GetCounter = channel.unary_unary(
                '/dcsm.SharedWorkingMemoryService/GetCounter',
                request_serializer=swm__service__pb2.DistributedCounterRequest.SerializeToString,
                response_deserializer=swm__service__pb2.CounterValueResponse.FromString,
                _registered_method=True)


class SharedWorkingMemoryServiceServicer(object):
    """Shared Working Memory Service (SWM)
    """

    def PublishKEMToSWM(self, request, context):
        """Publishes a KEM to SWM. May also initiate persistence/update in GLM.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToSWMEvents(self, request, context):
        """Subscribes to events occurring in SWM (e.g., new KEMs appearing).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySWM(self, request, context):
        """Queries active KEMs directly from SWM (from its cache).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadKEMsFromGLM(self, request, context):
        """Requests loading of KEMs from GLM into SWM (into SWM's cache).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireLock(self, request, context):
        """--- RPCs for Distributed Lock Management ---
        Attempts to acquire a lock on a resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Releases a previously acquired lock.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLockInfo(self, request, context):
        """Gets information about the current lock status for a resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementCounter(self, request, context):
        """--- RPCs for Distributed Counters ---
        Atomically increments (or decrements) the value of a counter.
        If the counter does not exist, it is created with the value of increment_by.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCounter(self, request, context):
        """Gets the current value of a counter.
        If the counter does not exist, may return an error or a default value (e.g., 0).
        TODO: Add DeleteCounter(DistributedCounterRequest) returns (google.protobuf.Empty) in the future.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SharedWorkingMemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishKEMToSWM': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishKEMToSWM,
                    request_deserializer=swm__service__pb2.PublishKEMToSWMRequest.FromString,
                    response_serializer=swm__service__pb2.PublishKEMToSWMResponse.SerializeToString,
            ),
            'SubscribeToSWMEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToSWMEvents,
                    request_deserializer=swm__service__pb2.SubscribeToSWMEventsRequest.FromString,
                    response_serializer=swm__service__pb2.SWMMemoryEvent.SerializeToString,
            ),
            'QuerySWM': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySWM,
                    request_deserializer=swm__service__pb2.QuerySWMRequest.FromString,
                    response_serializer=swm__service__pb2.QuerySWMResponse.SerializeToString,
            ),
            'LoadKEMsFromGLM': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadKEMsFromGLM,
                    request_deserializer=swm__service__pb2.LoadKEMsFromGLMRequest.FromString,
                    response_serializer=swm__service__pb2.LoadKEMsFromGLMResponse.SerializeToString,
            ),
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=swm__service__pb2.AcquireLockRequest.FromString,
                    response_serializer=swm__service__pb2.AcquireLockResponse.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=swm__service__pb2.ReleaseLockRequest.FromString,
                    response_serializer=swm__service__pb2.ReleaseLockResponse.SerializeToString,
            ),
            'GetLockInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLockInfo,
                    request_deserializer=swm__service__pb2.GetLockInfoRequest.FromString,
                    response_serializer=swm__service__pb2.LockInfo.SerializeToString,
            ),
            'IncrementCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementCounter,
                    request_deserializer=swm__service__pb2.IncrementCounterRequest.FromString,
                    response_serializer=swm__service__pb2.CounterValueResponse.SerializeToString,
            ),
            'GetCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCounter,
                    request_deserializer=swm__service__pb2.DistributedCounterRequest.FromString,
                    response_serializer=swm__service__pb2.CounterValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcsm.SharedWorkingMemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcsm.SharedWorkingMemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SharedWorkingMemoryService(object):
    """Shared Working Memory Service (SWM)
    """

    @staticmethod
    def PublishKEMToSWM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/PublishKEMToSWM',
            swm__service__pb2.PublishKEMToSWMRequest.SerializeToString,
            swm__service__pb2.PublishKEMToSWMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToSWMEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/SubscribeToSWMEvents',
            swm__service__pb2.SubscribeToSWMEventsRequest.SerializeToString,
            swm__service__pb2.SWMMemoryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySWM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/QuerySWM',
            swm__service__pb2.QuerySWMRequest.SerializeToString,
            swm__service__pb2.QuerySWMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadKEMsFromGLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/LoadKEMsFromGLM',
            swm__service__pb2.LoadKEMsFromGLMRequest.SerializeToString,
            swm__service__pb2.LoadKEMsFromGLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/AcquireLock',
            swm__service__pb2.AcquireLockRequest.SerializeToString,
            swm__service__pb2.AcquireLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/ReleaseLock',
            swm__service__pb2.ReleaseLockRequest.SerializeToString,
            swm__service__pb2.ReleaseLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLockInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/GetLockInfo',
            swm__service__pb2.GetLockInfoRequest.SerializeToString,
            swm__service__pb2.LockInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/IncrementCounter',
            swm__service__pb2.IncrementCounterRequest.SerializeToString,
            swm__service__pb2.CounterValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcsm.SharedWorkingMemoryService/GetCounter',
            swm__service__pb2.DistributedCounterRequest.SerializeToString,
            swm__service__pb2.CounterValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
